'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Company', [
      { name: 'VASCO', ContactInfoId: 24, CountryId:246 },
      { name: 'Branson Air Express', ContactInfoId: 25, CountryId: 239},
      { name: 'Angara Airlines', ContactInfoId: 26, CountryId: 184},
      { name: 'Star Peru', ContactInfoId: 27, CountryId:174 },
      { name: 'Air Burkina', ContactInfoId: 28, CountryId: 36},
      { name: 'Avianca', ContactInfoId: 29, CountryId: 49},
      { name: 'Maya Island Air', ContactInfoId: 30, CountryId:23 },
      { name: 'Albawings', ContactInfoId: 31, CountryId:3 },
      { name: 'Blue Air', ContactInfoId: 32, CountryId:183 },
      { name: 'Helvetic Airways', ContactInfoId: 33, CountryId:219 },
      { name: "Sun d'Or Airlines", ContactInfoId: 34, CountryId:107 },
      { name: 'Passaredo Linhas Aéreas', ContactInfoId: 35, CountryId:31 },
      { name: 'Binter Cabo Verde', ContactInfoId: 36, CountryId:41 },
      { name: 'Air Chathams', ContactInfoId: 37, CountryId:158 },
      { name: 'Air Choice One', ContactInfoId: 38 , CountryId:239},
      { name: 'Pacificair', ContactInfoId: 39, CountryId:175 },
      { name: 'Air Inuit', ContactInfoId: 40 , CountryId:40},
      { name: 'Jubba Airways', ContactInfoId: 41 , CountryId:207},
      { name: 'Silver Airways', ContactInfoId: 42, CountryId: 239},
      { name: 'Airline Urga', ContactInfoId: 43, CountryId: 236},
      { name: 'Air Philip', ContactInfoId: 44 , CountryId:210},
      { name: 'Avior Regional', ContactInfoId: 45, CountryId:245 },
      { name: 'Air Antilles', ContactInfoId: 46 , CountryId:75},
      { name: 'Tarco Aviation', ContactInfoId: 47, CountryId:214 },
      { name: 'Sichuan Airlines', ContactInfoId: 48, CountryId: 46},
      { name: 'Malawi Airlines', ContactInfoId: 49 , CountryId:132},
      { name: 'Boutique Air', ContactInfoId: 50, CountryId: 239},
      { name: 'Gazpromavia', ContactInfoId: 51, CountryId: 184},
      { name: 'FlyDamas', ContactInfoId: 52, CountryId: 220},
      { name: 'Kenn Borek Air', ContactInfoId: 53, CountryId: 40},
      { name: 'Airnorth', ContactInfoId: 54 , CountryId:14},
      { name: 'Star East Airlines', ContactInfoId: 55, CountryId:183 },
      { name: 'Warbelows Air', ContactInfoId: 56, CountryId: 239},
      { name: 'Airlink' , ContactInfoId: 57, CountryId:208},
      { name: 'Bassaka Air' , ContactInfoId: 58, CountryId:38},
      { name: 'Aeromexico Connect', ContactInfoId: 59 , CountryId:142},
      { name: 'FlyOne', ContactInfoId: 60 , CountryId:45},
      { name: 'FlyMontserrat', ContactInfoId: 61 , CountryId:148},
      { name: 'SmartAvia', ContactInfoId: 62, CountryId:184},
      { name: 'ASL Airlines France', ContactInfoId: 63 , CountryId:75},
      { name: 'Rutaca Airlines' , ContactInfoId: 64, CountryId:245},
      { name: 'Canadian North', ContactInfoId: 65, CountryId:40},
      { name: 'TAG Airlines', ContactInfoId: 66, CountryId: 239},
      { name: 'CemAir', ContactInfoId: 67, CountryId: 208},
      { name: 'TUI fly Nordic', ContactInfoId: 68, CountryId:218},
      { name: 'Air Timor', ContactInfoId: 69, CountryId: 63},
      { name: 'Israir Airlines', ContactInfoId: 70, CountryId:107 },
      { name: 'Solaseed Air', ContactInfoId: 71, CountryId: 111},
      { name: 'Aklak Air', ContactInfoId: 72, CountryId: 40},
      { name: 'Niger Airlines' , ContactInfoId: 73, CountryId:161},
      { name: 'Orbest', ContactInfoId: 74, CountryId: 212},
      { name: 'Cham Wings Airlines', ContactInfoId: 75, CountryId:220 },
      { name: 'ALROSA', ContactInfoId: 76, CountryId: 184},
      { name: 'SaudiGulf', ContactInfoId: 77, CountryId: 196},
      { name: 'SmartLynx Airlines Estonia', ContactInfoId: 78, CountryId:69 },
      { name: 'Madagasikara Airways', ContactInfoId: 79, CountryId: 131},
      { name: 'Sylt Air', ContactInfoId: 80, CountryId:82 },
      { name: 'First Air', ContactInfoId: 81, CountryId: 40},
      { name: 'MAYAir', ContactInfoId: 82 , CountryId:142},
      { name: 'Air Panama' , ContactInfoId: 83, CountryId:171},
      { name: 'Elite Airways', ContactInfoId: 84, CountryId: 239},
      { name: 'RusLine', ContactInfoId: 85, CountryId:184 },
      { name: 'Federal Airlines', ContactInfoId: 86, CountryId:208 },
      { name: 'Mann Yadanarpon Airlines', ContactInfoId: 87, CountryId:151 },
      { name: 'TransNusa', ContactInfoId: 88 , CountryId:102},
      { name: 'Bering Air', ContactInfoId: 89 , CountryId:239},
      { name: 'STP Airways', ContactInfoId: 90, CountryId: 195},
      { name: 'Fly Mid Africa', ContactInfoId: 91 , CountryId:80},
      { name: 'BHAir', ContactInfoId: 92, CountryId:35 },
      { name: 'EcoJet', ContactInfoId: 93 , CountryId:27},
      { name: 'Myanmar Airways International', ContactInfoId: 94, CountryId:151 },
      { name: 'Regional Air', ContactInfoId: 95, CountryId: 223},
      { name: 'Pacific Coastal Airlines', ContactInfoId: 96 , CountryId:40},
      { name: 'Air Tindi', ContactInfoId: 97 , CountryId:40},
      { name: 'Afriqiyah Airways', ContactInfoId: 98 , CountryId:125},
      { name: 'EWA Air', ContactInfoId: 99, CountryId:75 },
      { name: 'LATAM Colombia' , ContactInfoId: 100, CountryId:49},
      { name: 'PAL Express' , ContactInfoId: 101, CountryId:175},
      { name: 'Jetstar Asia', ContactInfoId: 102, CountryId:202},
      { name: 'Air Arabia Maroc', ContactInfoId: 103 , CountryId:149},
      { name: 'Fly540', ContactInfoId: 104 , CountryId:115},
      { name: 'Indigo', ContactInfoId: 105 , CountryId:101},
      { name: 'Jeju Air', ContactInfoId: 106, CountryId:110 },
      { name: 'Lucky Air', ContactInfoId: 107, CountryId: 46},
      { name: 'StarFlyer', ContactInfoId: 108 , CountryId:111},
      { name: 'TruJet', ContactInfoId: 109, CountryId:101 },
      { name: 'Ravn Alaska' , ContactInfoId: 110, CountryId:239},
      { name: 'Eurowings', ContactInfoId: 111, CountryId:82},
      { name: 'Onur Air', ContactInfoId: 112, CountryId: 230},
      { name: 'Interjet', ContactInfoId: 113 , CountryId:142},
      { name: 'Wright Air Service', ContactInfoId: 114, CountryId:239 },
      { name: 'Fly All Ways', ContactInfoId: 115 , CountryId:215},
      { name: 'Pan Pacific Airlines', ContactInfoId: 116, CountryId:175 },
      { name: 'Congo Airways', ContactInfoId: 117, CountryId: 58},
      { name: 'Air Changan', ContactInfoId: 118 , CountryId:46},
      { name: 'Dana Air', ContactInfoId: 119, CountryId:161 },
      { name: 'Cape Air', ContactInfoId: 120 , CountryId:239},
      { name: 'Central Mountain Air', ContactInfoId: 121, CountryId: 40},
      { name: 'Tropic Air', ContactInfoId: 122, CountryId: 23},
      { name: 'Caicos Express Airways', ContactInfoId: 123 , CountryId:230},
      { name: 'SATENA', ContactInfoId: 124, CountryId: 49},
      { name: 'Air Moldova', ContactInfoId: 125, CountryId:144 },
      { name: 'Avior Airlines' , ContactInfoId: 126, CountryId:245},
      { name: 'Jet Airways', ContactInfoId: 127 , CountryId:101},
      { name: 'Southern Airways Express', ContactInfoId: 128 , CountryId:239},
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Company', null, {});
  }
};